import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { MobileBottomNavbar, Sidebar, TopNavBar } from "@/components/shared";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="h-screen w-full">
          <TopNavBar />
          <div className="flex h-full w-full pt-12">
            <div className="hidden md:block">
              <Sidebar />
            </div>

            {children}
          </div>
          <div className="bottom-0 fixed flex md:hidden">
            <MobileBottomNavbar />
          </div>
        </div>
      </body>
    </html>
  );
}
